name: 'NPM Custom Action'
description: 'This is used for installing and caching NPM packages'
inputs:
  directory-path:
    description: 'The path to cache'
    required: true
runs:
  using: "composite"
  steps:
  - name: Cache NPM Dependencies
    uses: actions/cache@v4
    with:
      path: ${{inputs.directory-path}}
      key: ${{ runner.os }}-${{inputs.directory-path}}-${{ hashFiles('package-lock.json') }}

  - name: Install Dependencies
    run: npm install
    shell: bash
