apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    # You should replace these with your actual domain and email
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: rahulkumar.singh0801@gmail.com # your-email@example.com
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
    - http01:
        ingress:
          class: nginx
