name: Setup Kubernetes Environment

on:
  workflow_dispatch:
    inputs:
      install_ingress:
        description: 'Install Ingress'
        required: false
        default: false
        type: boolean
      install_cert_manager:
        description: 'Install Cert-Manager'
        required: false
        default: false
        type: boolean
      install_keda:
        description: 'Install KEDA'
        required: false
        default: false
        type: boolean
jobs:
  k8s-setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set Kubeconfig
      uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{secrets.KUBECONFIG_K8SCLUSTER_SURAJ}}

    - name: Fetch K8s Cluster Details
      run: |
        kubectl version
        echo --------------------------------------------
        kubectl get nodes

    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: latest

    - name: Install Ingress Controller
      if: ${{ inputs.install_ingress == true }}
      run: |
        kubectl create namespace ingress-nginx --dry-run=client -o yaml | kubectl apply -f -
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update
        helm install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx --set controller.publishService.enabled=true --set controller.healthCheckPath="/healthz"
        
        # Patch Azure Load Balancer health probe path
        kubectl annotate service ingress-nginx-controller -n ingress-nginx "service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path=/healthz" --overwrite
        
    - name: Install Cert-Manager
      if: ${{ inputs.install_cert_manager == true }}
      run: |
        kubectl create namespace cert-manager --dry-run=client -o yaml | kubectl apply -f -
        kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.17.1/cert-manager.crds.yaml
        helm repo add jetstack https://charts.jetstack.io
        helm repo update
        helm install cert-manager jetstack/cert-manager --namespace cert-manager --version v1.17.1

    - name: Verify Installations
      run: |
        kubectl get pods -n ingress-nginx
        kubectl get pods -n cert-manager
